<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <OptmizationPreference>Size</OptmizationPreference>
    <StackTraceSupport>true</StackTraceSupport>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Google.GenAI" Version="1.24.0" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.23.0" />
    <PackageReference Include="Mscc.GenerativeAI.Microsoft" Version="3.1.0" />
    <PackageReference Include="NetCord" Version="1.0.0-beta.28" />
    <PackageReference Include="NetCord.Services" Version="1.0.0-beta.28" />
  </ItemGroup>

</Project>
